services:
  discovery-server:
    build: infra/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - ewm-net
    environment:
      - EUREKA_PORT=8761
      - EUREKA_HOST=discovery-server
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 20s
      retries: 3
      start_period: 20s

  config-server:
    build: infra/config-server
    container_name: config-server
    ports:
      - "9091:9091"
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - EUREKA_HOST=discovery-server
      - EUREKA_PORT=8761
      - CONFIG_SERVER_PORT=9091
      - CONFIG_SERVER_HOST=config-server
    healthcheck:
      test: "curl --fail --silent localhost:9091/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 40s
      retries: 3
      start_period: 20s

  stats-server:
    build: stats/stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - EUREKA_HOST=discovery-server
      - EUREKA_PORT=8761
      - APP_PROFILE=dev
      - STATS_SERVER_PORT=9090
      - STATS_SERVER_HOST=stats-server
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: "curl --fail --silent localhost:9090/actuator/health | grep UP || exit 1"
      timeout: 20s
      interval: 5s
      retries: 5
      start_period: 25s

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ewm-stats
    networks:
      - ewm-net
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 15

  categories-server:
    build: core/categories-server
    container_name: ewm-categories-server
    ports:
      - "8092:8092"
    depends_on:
      ewm-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - EUREKA_HOST=discovery-server
      - EUREKA_PORT=8761
      - APP_PROFILE=dev
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - CATEGORY_SERVICE_PORT=8092
      - CATEGORY_SERVICE_HOST=categories-server
    healthcheck:
      test: "curl --fail --silent localhost:8092/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 10s
      retries: 4
      start_period: 10s

  compilations-server:
    build: core/compilations-server
    container_name: ewm-compilations-server
    ports:
      - "8093:8093"
    depends_on:
      categories-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - EUREKA_HOST=discovery-server
      - EUREKA_PORT=8761
      - APP_PROFILE=dev
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - COMPILATION_SERVICE_PORT=8093
      - COMPILATION_SERVICE_HOST=compilations-server
    healthcheck:
      test: "curl --fail --silent localhost:8093/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 10s
      retries: 4
      start_period: 10s

  events-server:
    build: core/events-server
    container_name: ewm-events-server
    ports:
      - "8094:8094"
    depends_on:
      compilations-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - EUREKA_HOST=discovery-server
      - EUREKA_PORT=8761
      - APP_PROFILE=dev
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - EVENT_SERVICE_PORT=8094
      - EVENT_SERVICE_HOST=events-server
      - STATS_SERVER_NAME=stats-server
    healthcheck:
      test: "curl --fail --silent localhost:8094/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 10s
      retries: 4
      start_period: 10s

  requests-user-server:
    build: core/requests-user-server
    container_name: ewm-requests-user-server
    ports:
      - "8095:8095"
    depends_on:
      events-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - EUREKA_HOST=discovery-server
      - EUREKA_PORT=8761
      - APP_PROFILE=dev
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - REQUEST_SERVICE_PORT=8095
      - REQUEST_SERVICE_HOST=requests-user-server
    healthcheck:
      test: "curl --fail --silent localhost:8095/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 10s
      retries: 4
      start_period: 10s

  user-service:
    build: core/user-service
    container_name: ewm-user-service
    ports:
      - "8096:8096"
    depends_on:
      requests-user-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - EUREKA_HOST=discovery-server
      - EUREKA_PORT=8761
      - APP_PROFILE=dev
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - USER_SERVICE_PORT=8096
      - USER_SERVICE_HOST=user-service
    healthcheck:
      test: "curl --fail --silent localhost:8096/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 40s
      retries: 3
      start_period: 20s

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-main-db
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ewm
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 15

  gateway-server:
    build: infra/gateway-server
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      categories-server:
        condition: service_healthy
      compilations-server:
        condition: service_healthy
      events-server:
        condition: service_healthy
      requests-user-server:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - EUREKA_HOST=discovery-server
      - EUREKA_PORT=8761
      - APP_PROFILE=dev
      - GATEWAY_SERVICE_PORT=8080
      - GATEWAY_SERVER_HOST=gateway-server
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      timeout: 20s
      interval: 5s
      retries: 5
      start_period: 25s

networks:
  ewm-net:
