
create TABLE IF NOT EXISTS compilation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pinned boolean NOT NULL,
  title varchar(50) NOT NULL
);

create TABLE IF NOT EXISTS compilation_events (
  compilation_id BIGINT NOT NULL,
  event BIGINT NOT NULL
);

