server:
  port: ${EUREKA_PORT}

eureka:
  instance:
    hostname: ${EUREKA_HOST}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
