
create TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    name VARCHAR(250) NOT NULL
);

create TABLE IF NOT EXISTS followers (
    follower_id BIGINT NOT NULL,
    followed_id BIGINT NOT NULL,
    CONSTRAINT followers_follower FOREIGN KEY (follower_id) REFERENCES users(id) ON delete CASCADE,
    CONSTRAINT followers_followed FOREIGN KEY (followed_id) REFERENCES users(id) ON delete CASCADE
);
