
create TABLE IF NOT EXISTS user_request (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created TIMESTAMP NOT NULL,
  event_id BIGINT NOT NULL,
  requester_id BIGINT NOT NULL,
  status varchar(50) NOT NULL,
  UNIQUE (event_id, requester_id)
);
