spring:
  profiles.active: ${APP_PROFILE:default}
  application:
    name: events-server
  config:
    import: "configserver:"
    fail-fast: true
    retry:
      useRandomPolicy: true
      max-interval: 6000
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server


eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
  instance:
    hostname: ${EVENT_SERVICE_HOST}
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${EVENT_SERVICE_PORT}-${random.value}}
    leaseRenewalIntervalInSeconds: 30

